version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "No Installation anymore...."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip lambda_function.py eod_usrate.py dataUtil.py Stk_eodfetch.py Product_List
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name myFinData --zip-file fileb://deployment_package.zip
      - echo "DONE!!"