service: fin-cron-data

# configValidationMode: error

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  
provider:
  name: aws
  runtime: python3.10
  region: us-east-2
  profile: ServerLessUser
  timeout: 120     # default is 6 sec
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'S3:PutObject'
            - 'S3:GetObject'
            - 's3:HeadObject'  # Add this
            - 'S3:DeleteObject'
          Resource: 
            - "arn:aws:s3:::workingplace/*"
            - "arn:aws:s3:::fin-modal-data/*"
        - Effect: Allow
          Action: 'S3:ListBucket'
          Resource: 
            - "arn:aws:s3:::workingplace"
            - "arn:aws:s3:::fin-modal-data"

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      # - schedule: cron(0/15 13-21 ? * MON-FRI *)
      - schedule: cron(0/10 13-21 ? * MON-FRI *)
      - schedule: cron(0/10 21-00 ? * MON-FRI *)
  optHandler:
    handler: opt_handler.run
    events:
      # Invoke Lambda function NYT 9:30-4:00 pm from Fri
      - schedule: cron(0/10 12-21 ? * MON-FRI *)
  yfinHandler:
    handler: yfin_handler.run
    events:
      # Invoke Lambda function every HKT 9:30 am from Mon to US Friday close
      - schedule: cron(0/0 1-22 ? * MON-FRI *)
  yfus30minEOD:
    handler: eoddata_minhandler_us.run
    events:
      # Invoke Lambda function every night 
      - schedule: cron(05 00 ? * TUE-SAT *)   
  yfasia30minEOD:
    handler: eoddata_minhandler_asia.run
    events:
      # Invoke Lambda function every night 
      - schedule: cron(00 10 ? * MON-FRI *)   
  fffHandler:
    handler: fff_handler.run
    events:
      - schedule: cron(0 0 1 * ? *)    
  usrateHandler:
    handler: usrate_handler.run
    events:
      - schedule: cron(1 21 ? * MON-FRI *)    
  FXrateHandler:
    handler: fx_handler.run
    events:
      - schedule: cron(0 0-23 ? * SUN-SAT *)    
  FXHistHandler:
    handler: fxeod_handler.run
    events:
      - schedule: cron(10 21 ? * SUN-SAT *)    
  yfNewshandler:
    handler: yf-news-collect.run
    events:
      - schedule: cron(1 * * * ? *) # 11:30 pm EDT (UTC-4) every day